apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-sample
  namespace: openshift-gitops
  finalizers:
    #cascade delete of resources
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nodejs-sample
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      #if app-directory includes kustomization.yaml, recurse must be false
      recurse: false
    path: openshift
    repoURL: https://github.com/samisalkosuo/nodejs-sample
    targetRevision: main
  syncPolicy:
#    syncOptions:
#    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
