apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  failureDomain: host
  replicated:
    size: 3
