apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storageclass-block.yaml
- storageclass-filesystem.yaml
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  