apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cephblockpool-replicapool.yaml
- storageclass-block.yaml
- cephfilesystem-cephfs.yaml
- storageclass-filesystem.yaml
- test-claims.yaml
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
#remove default storage class
patches:
- patch: |-
  - op: replace
    path: "/metadata/annotations/storageclass.kubernetes.io/is-default-class"
    value: false
  target:
    kind: StorageClass
    name: ibmc-vpc-block-10iops-tier

