kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-block
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: rook-ceph-block
  volumeMode: Block
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-fs
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: rook-ceph-fs
  volumeMode: Filesystem
