apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: waiops-demo
  namespace: cp4waiops
spec:
  size: small
  storageClass: ocs-storagecluster-cephfs
  storageClassLargeBlock: ocs-storagecluster-ceph-rbd
  imagePullSecret: ibm-entitlement-key
  license:
    accept: true
  pakModules:
  - name: aiopsFoundation
    enabled: true
  - name: applicationManager
    enabled: true
  - name: aiManager
    enabled: true
  - name: connection
    enabled: false