apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: cp4waiops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  IBM_REGISTRY: cp.icr.io
  IBM_REGISTRY_USER: cp
  IBM_REGISTRY_KEY: modifythisifneeded
