kind: IAConfig
apiVersion: aiops.ibm.com/v1alpha1
metadata:
  name: ibm-ia-installer
  namespace: cp4waiops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  imagePullSecret: ibm-entitlement-key
  infraAutoComposableComponents:
    - enabled: true
      name: ibm-management-im-install
      spec:
        iminstall:
          #TODO: change to correct cluster name, check docs https://www.ibm.com/docs/en/cloud-paks/cloud-pak-watson-aiops/3.7.1?topic=automation-online-installation
          #
          applicationDomain: inframgmtinstall.apps.demo10.cloud.techzone51.net
          imagePullPolicy: Always
          imagePullSecret: ibm-entitlement-key
          initialAdminGroupName: admin
          license:
            accept: true
    - enabled: true
      name: ibm-management-cam-install
      spec: {}
  license:
    accept: true
  storageClass: rook-ceph-fs
  storageClassLargeBlock: rook-ceph-block