apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#uncomment if namespace not created otherwise
#- namespace.yaml
- subscription.yaml
- operator-group.yaml
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  