apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mssql-statefulset.yaml
- namespace.yaml
- secret.yaml
- service.yaml
- mssql-scc.yaml
- serviceaccount.yaml
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  