kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-mssql
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowedCapabilities: 
- '*'
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:mssql:mssql-sa
volumes: 
- '*'
