kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-mssql
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:mssql:mssql-sa
