apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rpa-demo-setup
  namespace: openshift-gitops  
  finalizers:
    #cascade delete of resources
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc  
  project: default
  source:
    directory:
      recurse: false
    path: rpa-demo/setup
    repoURL: https://github.com/samisalkosuo/gitops-public
    targetRevision: HEAD
  syncPolicy:
#    syncOptions:
#    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
