apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- infrastructure-automation-subscription.yaml
- ibm-entitlement-key-secret.yaml
- aimanager-subscription.yaml
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  