apiVersion: v1
kind: Namespace
metadata:
  name: cp4waiops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  finalizers:
  - kubernetes
