apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-db2
  namespace: db2
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  channel: v110508.0
  installPlanApproval: Automatic
  name: db2u-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
