apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  #change storage for ceph cluster 
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: ibmc-vpc-block-10iops-tier
        resources:
          requests:
            storage: 10Gi
  storage:
    storageClassDeviceSets:
    - name: device-set-1
      count: 3
      portable: false
      encrypted: false
      config:
        osdsPerDevice: "1"
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 500Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: ibmc-vpc-block-10iops-tier
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
