apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  #change storage for ceph cluster 
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: ibmc-vpc-block-10iops-tier
        resources:
          requests:
            storage: 10Gi
  storage:
  #app=rook-ceph-osd-prepare
    storageClassDeviceSets:
    - name: device-set-1
      count: 3
      portable: false
      encrypted: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 500Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: ibmc-vpc-block-10iops-tier
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
      preparePlacement:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
      placement: 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
              topologyKey: kubernetes.io/hostname
        # topologySpreadConstraints:
        # #only one pod per host
        # - maxSkew: 1
        #   topologyKey: kubernetes.io/hostname
        #   #change to ScheduleAnyway if allowing pods in same host
        #   whenUnsatisfiable: DoNotSchedule
        #   labelSelector:
        #     matchExpressions:
        #     - key: app
        #       operator: In
        #       values:
        #         - rook-ceph-osd
