apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: first-tenant-secret
  namespace: ibm-rpa-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
stringData:
  name: admin
  email: "sami.salkosuo@fi.ibm.com"


