apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-automation-processmining
  namespace: ibm-pm-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  channel: v2.0
  installPlanApproval: Automatic
  name: ibm-automation-processmining
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
